### ISSUE TITLE
Using diary.js with di.js

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/diary.js#2]
This is more like a question / request for comments regarding usage of diary.js in the di.js container. 

Currently playing with various ideas in this project: https://github.com/pkozlowski-opensource/batmobile.js and failing to get a working system that I would feel OK with. To make things concrete let's take this class as an example:

``` javascript
import {Diary} from 'diary';

export class Engine {

  constructor() {
    this.logger = Diary.logger('engine');
  }

  start() {
    this.logger.info('Starting hydrogen-boosted engine!');
  }
}
```

As you can see, currently Diary.js is using a static call (`Diary.logger('engine')`) or a constructor with an argument (`new Diary('engine')`) to create a new group logger.

In the code example above I'm "cheating". Ideally I would like to directly inject a logger, for the unit-testing purposes, something like:

``` javascript
import {Diary} from 'diary';

export class Engine {

  constructor(@Inject(Diary.logger('engine')) logger) {
    this.logger = logger;
  }
}
```

which doesn't work with the current DI implementation. Was also playing with the following possibility:

``` javascript
import {Diary} from 'diary';

export class Engine {

  constructor(@Inject(Diary) Diary) {
    this.logger = Diary.logger('engine');
  }
}
```

but once again, this would require changes to the current DI as it doesn't allow us to register instances (at least I didn't see any way of doing so).

I'm not sure if I'm thinking completely wrong about this di.js + Diary.js combo (and we shouldn't manage loggers in the DI container) or is it something missing in the di or Diary.
Continuing to play with different ideas but would be grateful for comments / input.

**Comment by iammerrick** [comment]
Would love to hear @vojtajina input on this.

**Comment by pkozlowski-opensource** [comment]
Me too, just didn't want to summon the busy man :-) But yeh, apart from Diary.js concerns there is more generic questions for DI IMO, that is:
- how to register pre-instantiated objects in the DI container (a factory function?)
- how to register multiple instances of the same class and inject a chosen instance

Then again, don't want to hijack the thread for the DI topics, let's focus on the Diary.js usage scenario here.

**Comment by iammerrick** [comment]
I'm still having a hard time wrapping my head around the new DI.js myself. I would love to get some answers.

**Comment by vojtajina** [comment]
@pkozlowski-opensource I think you can achieve your second version, with this:

``` js
@Provide(Diary)
function diaryClassFactory() {
  return Diary;
}
```

Now, with logger, I think you want something like this (basically your first example):

``` js
import {Diary} from 'diary';

export class Engine {

  @Inject(Diary('engine'))
  constructor(logger) {
    this.logger = logger;
  }
}
```

This instance of logger has to be not cached (opposite of singleton).

``` js
class RealDiary {
  // this is the current Diary class

  constructor(@Inject(Diary.name) name) {
    this.name = name;
  }
}

var Diary = function(name) {
  @Provide(Diary.name)
  var nameProvider = function() {
    return name;
  };
  return function(@Inject(Injector) injector) {
    return injector.createChild([RealDiary, nameProvides], []).get(RealDiary);
  }
};

//  just a token for DI
Diary.name = function() {};
```

I haven't tried this, but I think this crazy code should do it (at least in theory). It should give us the syntax we want, right? I think this "feature" might have other use cases (eg. you could inject a specific DOM element with  `@Inject(Element('.some-cls'))`, in which case we could probably make this crazy code part of the DI.

**Comment by IgorMinar** [comment]
could we improve the DI so that we could just do:

```
import {Diary} from 'diary';

export class Engine {

  @Inject(Diary)
  constructor(logger) {
    this.logger = logger;
  }
}
```

Note that `"engine"` is not specified anywhere, but DI would still provide Engine specific logger to the constructor. This would require making it possible to provide the injected class to the provider that we are injecting.

**Comment by vojtajina** [comment]
Yes. Sorry, I forgot to mention this option. This is possible.

I'm just not sure if there is any other use case (besides logger) for this
feature (provider knowing who is asking for that instance). Can you guys
think of any other use case?

Also, the provider would get the class or factory function (not the actual
requestor instance, as that instance does not exist when resolving deps),
so Diary will have to figure out the name from the class/factory function.

**Comment by iammerrick** [comment]
I was thinking we could use the module id as part of the construction unfortunately... It's require.js thing and is not currently in ES6 modules though it is in the works?

https://twitter.com/littlecalculist/status/436345443048382464

**Comment by IgorMinar** [comment]
@iammerrick Since we'll likely end up with only one class per module, it doesn't make a difference for us.

@vojtajina I think that the feature is not useful for regular code, but infrastructure objects like loggers, caches, serializers would benefit from it.

**Comment by pkozlowski-opensource** [comment]
@vojtajina and all - thnx for the very valuable input, you guys are full of ideas! Now, I had a closer look at some of the items and here are some more thoughts.

##### Injection of constructor functions doesn't seem to work in a browser

I've tried the following before opening this issue:

``` javascript
@Provide(Diary)
function diaryClassFactory() {
  return Diary;
}
```

but it didn't work and from my brief debugging this factory-function powered provider was registered under the `"Diary"` token (as String). I'm not sure if this is due to something in DI or rather due to transpilation or (most probably) me being blind. Will dig into it more and will open an issue in DI if needed.

But this idea of using a factory function to inject constructor functions raises a questions - _shouldn't we have a syntax / annotation to indicate that a given "thing" should be taken "as-is", instead of trying to use a constructor function (in this example) to produce new objects_? So we could write:

``` javascript
import {Diary} from 'diary';

export class Engine {

  @Instance(Diary)
  constructor(Diary) {
    this.logger = Diary.logger('engine');
  }
}
```

Or `@InjectInstance(Diary)` or whatever - basically sugar for a factory function.

##### Will try out crazy syntax :-)

Will see what is possible with the current injector when it comes to getting this syntax:

``` javascript
import {Diary} from 'diary';

export class Engine {

  constructor(@Inject(Diary.logger('engine')) logger) {
    this.logger = logger;
  }
}
```

Vojta, you are really creative, I would never come up with the proposed work-arround :-) In any case it would be great to have something like this baked-in in DI. BTW, previous paragraph made me realise that the semantic here is to inject a pre-baked instance so it should rather be `@InjectInstance(Diary.logger('engine')) logger`

##### Now about the "magic"

@IgorMinar it crossed my mind to simply write:

``` javascript
import {Diary} from 'diary';

export class Engine {

  @Inject(Diary)
  constructor(logger) {
    this.logger = logger;
  }
}
```

but somehow it felt "too magical". I mean, I couldn't come up with a good "story" to explain this syntax... and more importantly - how to pass an argument that indicates injection target (here: `Engine`)? Should it be the last argument to the factory function? Or a special annotation (`@InjectTarget`) so we could Diary's factory function as:

``` javascript
@Provide(Diary)
@TransientScope
function getLogger(@InjectTarget category) {
    return Diary.logger(category);
}
```

Well, anyway, dumping my brain here, not sure if my rambling is at least remotely understandable.... More reading / playing with the code ahead of me! I'm reading through https://docs.google.com/document/d/1LWxs4urzg-yQSzXOc_R8063Q14lemVqYcxd-Yp8BgZc/edit# now, maybe it will explain things...

**Comment by vojtajina** [comment]
@pkozlowski-opensource if the code you posted doesn't work, there is a bug in the DI, create an issue. I just tried this and it worked for me:

``` js
    class Diary {}

    @Provide(Diary)
    function provideDiary() {
      return Diary;
    }

    var injector = new Injector([provideDiary]);
    console.log(injector.get(Diary))
```

**Comment by pkozlowski-opensource** [comment]
@vojtajina just re-tested using a factory function to inject classes and it works, I must have messed something up when testing things initially. Sorry for the confusion.

Still there are 2 interesting topic remaining:
- making injectables aware of their injection target
- management of a transient scope without a need to create child injectors
  but I guess that those are better tackled as part of the di.js project. 

Closing this one, will dig into the topic some more and eventually open issue(s) in the di.js.  Once again, thnx for all the input!

**Comment by pkozlowski-opensource** [comment]
@vojtajina @IgorMinar @iammerrick sorry for spamming you guys here but just got super excited about one trick / finding that can make a very nice Diary.js / Di.js integration story. Let's assume we can create a simple integration module like so:

``` javascript
import {Diary} from 'diary';
import {Inject} from 'annotations';

var diaryLoggerFactory = function(groupName) {
  return Diary.logger(groupName);
};

export class Logger extends Inject {

  constructor(groupName) {
    super(function(){
      return diaryLoggerFactory(groupName);
    });
  }
};
```

This basically creates a new @Inject-like annotation (`@Logger`) that can be used like so:

``` javascript
import {Logger} from 'logger';

export class Engine {

  constructor(@Logger('engine') logger) {
    this.logger = logger;
  }
}
```

This is it! Just tested it locally and it seems to work all right!!! I guess it could be simplified even further if we can somehow know the injection target and make it available as the last (second) param to the @Inject annotation: https://github.com/angular/di.js/blob/master/src/annotations.js#L71

WDYT? Probably there is some awful hole in my reasoning here but I kind of really like this integration scenario.

**Comment by vojtajina** [comment]
This works as long as Diary don't have any other dependencies.
